"""Typed parameter constructors mirroring MATLAB `sp`, `pp`, and `params`."""

from spin_dynamics.parameters.constructors import (
    FIDPulseParameters,
    FIDSystemParameters,
    MatchedPulseParameters,
    MatchedSystemParameters,
    PulseParameters,
    SystemParameters,
    TunedOrigParameters,
    TunedPulseParameters,
    TunedSystemParameters,
    UntunedOrigParameters,
    UntunedPulseParameters,
    UntunedSystemParameters,
    set_params_ideal_fid,
    set_params_ideal,
    set_params_matched_jmr,
    set_params_matched_orig,
    set_params_matched_spa,
    set_params_tuned_jmr,
    set_params_tuned_orig,
    set_params_tuned_spa,
    set_params_untuned_jmr,
    set_params_untuned_orig,
    set_params_untuned_spa,
)

__all__ = [
    "FIDPulseParameters",
    "FIDSystemParameters",
    "MatchedPulseParameters",
    "MatchedSystemParameters",
    "PulseParameters",
    "SystemParameters",
    "TunedOrigParameters",
    "TunedPulseParameters",
    "TunedSystemParameters",
    "UntunedOrigParameters",
    "UntunedPulseParameters",
    "UntunedSystemParameters",
    "set_params_ideal",
    "set_params_ideal_fid",
    "set_params_matched_jmr",
    "set_params_matched_orig",
    "set_params_matched_spa",
    "set_params_tuned_jmr",
    "set_params_tuned_orig",
    "set_params_tuned_spa",
    "set_params_untuned_jmr",
    "set_params_untuned_orig",
    "set_params_untuned_spa",
]
